### ISSUE TITLE
Logo do jogo

### ISSUE THREAD

**Issue by winterjeferson** [winterjeferson/open-source-adventure#52]
Precisamos desenvolver um logo para o jogo.
Referências:

![f098af771fc0885e1197be2c98031961](https://user-images.githubusercontent.com/3902192/140335469-544cac63-3d92-4001-a804-6dfffe02133e.png)
![383b76d8a4ef8e03ea6277d20b87d911](https://user-images.githubusercontent.com/3902192/140335464-5fb93a84-2d1c-4733-a5d5-49eb7ae5a72e.jpg)
![f1ad3b05abe4a7696dc8d9a16322311c](https://user-images.githubusercontent.com/3902192/140335467-aa567125-b6e5-4ca7-b46c-9851d38b7d5c.jpg)

**Comment by fussyfangs** [comment]
![logo](https://user-images.githubusercontent.com/93674889/142130255-563c5e92-d111-432b-911f-188b89c62101.png)
