### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [winterjeferson/open-source-adventure#58]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by winterjeferson** [comment]
Olá!
O pessoal deu uma desanimada em contribuir.
Eu estou disposto a voltar, se mais alguém estiver.

Atenciosamente,
Jeferson Winter
Desenvolvedor Fullstack
http://jefersonwinter.com.br


Em qui., 29 de dez. de 2022 às 20:31, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi winterjeferson.

> Olá!
> O pessoal deu uma desanimada em contribuir.
> Eu estou disposto a voltar, se mais alguém estiver.

sou afim de contribuir sempre com vários tipos de projeto sendo abertos, fechados, mistos etc. tenho um interesse em ajudar esse projeto e sua mensagem é muito interessante, motivadora. vou fechar essa issue porque minha pergunta foi respondida, agora vou ver como posso contribuir.

**Comment by winterjeferson** [comment]
Seja bem vindo!

Atenciosamente,
Jeferson Winter
Desenvolvedor Fullstack
http://jefersonwinter.com.br


Em sex., 6 de jan. de 2023 às 18:38, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi winterjeferson.

> Seja bem vindo!
> Atenciosamente,
> Jeferson Winter
> Desenvolvedor Fullstack
> http://jefersonwinter.com.br/
> Em sex., 6 de jan. de 2023 às 18:38, Code Hangen ***@***.***>
escreveu:

vou ver como posso ajudar esse projeto.

*tenha um ótimo dia e obrigado novamente por esclarecer, responder minha dúvida*

**Comment by winterjeferson** [comment]
Certo!
Qualquer coisa, pode chamar

Atenciosamente,
Jeferson Winter
Desenvolvedor Fullstack
http://jefersonwinter.com.br


Em ter., 17 de jan. de 2023 às 04:25, Code Hangen ***@***.***>
escreveu:
